### ISSUE TITLE
Out of stock by default

### ISSUE THREAD

**Issue by octave** [solidusio-contrib/solidus_virtual_gift_card#64]
Hi guys,

I was wondering if a stock location needs to be setup for gift cards? Right now it is sold out unless I put the gift card as backorderable from a stock location. Is it the only way? It should bypass the stock location logic as it is virtual and doesn't need a stock location or isn't it possible?

Would we need a custom splitter like the `solidus_digital` extension?: https://github.com/solidusio-contrib/solidus_digital/blob/master/app/models/spree/stock/splitter/digital_splitter.rb

Thank you!

Octave

**Comment by seandawes** [comment]
Just curious but why not just create a new stock location being Virtual. How would this create an issue by just making a virtual warehouse? This way every product whether digital or physical is tied to a database of a warehouse. As than when it comes to reporting you can report by warehouse, brand, sku etc if building out reports

**Comment by hrdchz** [comment]
The issue seems to be something deeper in Solidus' Inventory system. Here is what I was able to find out trying to get gift cards set up using virtual warehouse:
 
**Store / Product configuration**

Stock Location "Virtual":
- Only "active" and "backorderable default" are checked. From the available settings it appears this should be a location for "non-physical" objects only

Shipping method "Ephemeral good":
- $0.00 shipping that applies to the "Ephemeral" category

Product / Variant "Gift Card":
- is a gift card
- does not track inventory
- shipping category "Ephemeral"
- stock location: Only "Virtual"

**Expected Behavior**

Add gift card to cart, complete purchase, process order and there should be no issue with shipping or backordering of the card.

**Results**

When the card is not backorderable: out of stock from product page

When the card is backorderable: order stays at backorder status regardless of the "virtual" stock location / "do not track inventory" option on the variant
 
When the card "does not track inventory" and has no stock locations: insufficient stock to process order


- "Do not track inventory" does not work as expected, possibly related: https://github.com/solidusio/solidus/pull/3338 

- What is "Fulfillable" actually supposed to do? Un-setting this does not seem to bypass shipping for products in this warehouse.

- Unless I have something backwards above the best way to get through this is to fake the inventory count for the Gift Card product and use that "Ephemeral" style shipping category

**Comment by hrdchz** [comment]
Hm. In your "Virtual" stock location if have "Fulfillable" unchecked but "Check stock on transfer" checked, things seem to work as expected?

**Comment by octave** [comment]
@hrdchz thank you! I confirm it works with this setting.

**Comment by octave** [comment]
@hrdchz How do you manage to have your variants only using "Virtual" stock locations? I don't see any options for that?

**Comment by hrdchz** [comment]
@octave I believe I disabled the "default" for my "Default" stock location temporarily and then created the Gift Card product. Hm, perhaps not. I have "propogate all variants" unchecked for "default". I believe that is what makes stocks for variants on variant creation.

There is likely some way to easily destroy the existing stocks for your variant in `rails c` but I'm not sure which models exactly we want to get rid of? Perhaps stock_items would do it.

Also my "Virtual" location only has two options checked: "Active" and "Check stock on transfer"

**Comment by octave** [comment]
@hrdchz You are right! I had to recreate the variants but then when assigning the variant to the "Virtual" location I had to make sure to check "Back Orderable" otherwise it would not let the checkout workflow start, only add to cart. Same for you?

**Comment by hrdchz** [comment]
hmm looks like in my stock page, I'm unable to even do anything with "backorderable": it is unchecked and disabled, and I'm unable to modify the quantity.

<img width="651" alt="Screen Shot 2020-03-24 at 2 48 02 PM" src="https://user-images.githubusercontent.com/50925553/77480218-8a60fa00-6dde-11ea-8c9f-71d57c4dbd6b.png">

**Comment by hrdchz** [comment]
@octave ... and I was able to complete checkout with a dummy card just now

**Comment by octave** [comment]
@hrdchz yes it does that as soon as you set the stock location, you have to check it when assigning, after that the only way is in the console. But how does it work with your check out process without it? Mine trig the error "Item is not in stock anymore".

![image](https://user-images.githubusercontent.com/343/77480524-1a9f3f00-6ddf-11ea-9dc1-92c9d775da4c.png)

**Comment by hrdchz** [comment]
@octave Unfortunately I only ever set this up once on a demo site a few months back. I hoped I had sufficient notes in here to recreate my work. I'm not sure now how exactly I set this up now. I will update this thread when I know more but that may not be for a while. If you have any success please do the same.

**Comment by hrdchz** [comment]
Also I feel like maybe I found some useful clues in https://github.com/solidusio/solidus/pull/3338 and its related issue, but I am working on something else right now

**Comment by octave** [comment]
Oh yeah it seems to be related to that issue! I will keep it on backordered in the meantime. Thanks again for your help!
